In [5]:
a = [1, 2, 3, 4, 5]
b = [1, 2, 3, 4, 5]
c = []
for i in range(0, 5):
    c.append(a[i] + b[i])
print(c)

[2, 4, 6, 8, 10]


In [6]:
import numpy as np
a = np.array(a)
b = np.array(b)
c = a + b
print(c)

[ 2  4  6  8 10]


In [7]:
b = np.arange(1, 16)
b_bool = b>5
b[b_bool] = 1 
print(b)

[1 2 3 4 5 1 1 1 1 1 1 1 1 1 1]


In [8]:
arr = np.arange(1, 10)
mat_3 = arr.reshape(3, 3)
arr = mat_3.reshape(-1)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [9]:
mat_1 = np.arange(10).reshape(2, -1)
print(mat_1)
mat_b = np.repeat(1, 10).reshape(2, -1)
print(mat_b)
np.concatenate([mat_1, mat_b], axis=1)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [10]:
np.vstack([mat_1, mat_b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.hstack([mat_1, mat_b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [12]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
#get the positions where elements of a and b match.
c = np.where(a==b)

In [13]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [14]:
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

In [15]:
arr = np.arange(9).reshape(3, 3)
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [16]:
arr[[1, 0, 2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [17]:
arr[:, [2, 1, 0]]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [19]:
arr[1, 1] = 7
arr

array([[0, 1, 2],
       [3, 7, 5],
       [6, 7, 8]])