In [1]:
import numpy as np
grid = np.zeros( (6,6), dtype = int )
aword = 'decaf'
x = 0   # where to put it
y = 3
for letter in aword:
    grid[ (y, x) ] = ord(letter) - 96
    x += 1
    if (x >= 6):
        break   # don't go outside the grid!
print(grid)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [4 5 3 1 6 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [26]:
def prettyprint( printme ):
    pretty = np.array([[" "," "," "," "," "," "],
                      [" "," "," "," "," "," "],
                      [" "," "," "," "," "," "],
                      [" "," "," "," "," "," "],
                      [" "," "," "," "," "," "],
                      [" "," "," "," "," "," "]])
    x=0
    for l in printme:
        y=0
        for e in l:
            if e>0: pretty[x,y]=(chr(e+64))
            y+=1
        x+=1
    
    print(pretty)

In [27]:
prettyprint(grid)

[[' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ']
 ['D' 'E' 'C' 'A' 'F' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ']]


In [28]:
def place(word):
    for x in range(6):
        for y in range(6):
            

SyntaxError: unexpected EOF while parsing (<ipython-input-28-2ea545d60614>, line 4)

In [125]:
def doesItFit(word, x, y):
    a =x
    b=y
    if horizontal(a, b, word, x, y):
        return "H"
    elif vertical(a, b, word, x, y):
        return "V"
    else: return "N"

In [126]:
def horizontal(b, word, x, y):
    for i in range(len(word)):
        if b == 6: return False
        if not grid[x, b] == 0 and not grid[x, b] == ord(word[b-y])-96:
            return False
        b+=1
    return True

In [127]:
def vertical(a, b, word, x, y):
    while a< 6:
        if a-x == len(word): return False
        if grid[a, y]==0 or grid[a, y]== ord(word[a-x]) -96:
            a+=1
        else: return False
    if 6-x >= len(word): return True
    else: return False

In [128]:
horizontal(0, "faced", 5, 0)

True

In [120]:
grid

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [4, 5, 3, 1, 6, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])